# Generated by Django 5.0.1 on 2026-03-10 04:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('backdrop_path', models.CharField(blank=True, max_length=255)),
                ('genres', models.JSONField(default=list)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('region', models.CharField(default='GLOBAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('release_year', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'movies',
                'indexes': [models.Index(fields=['tmdb_id'], name='movies_tmdb_id_472987_idx'), models.Index(fields=['region'], name='movies_region_16ddce_idx')],
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('backdrop_path', models.CharField(blank=True, max_length=255)),
                ('genres', models.JSONField(default=list)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('region', models.CharField(default='GLOBAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seasons', models.IntegerField()),
                ('episodes_per_season', models.IntegerField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('ended', 'Ended')], default='ongoing', max_length=20)),
            ],
            options={
                'db_table': 'tvshows',
                'indexes': [models.Index(fields=['tmdb_id'], name='tvshows_tmdb_id_ef2249_idx'), models.Index(fields=['region'], name='tvshows_region_5898e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tvshow', 'TV Show')], max_length=10)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
                'indexes': [models.Index(fields=['content_id', 'content_type'], name='ratings_content_cddc62_idx'), models.Index(fields=['user'], name='ratings_user_id_bd9bb9_idx')],
                'unique_together': {('user', 'content_id', 'content_type')},
            },
        ),
    ]
