# Generated by Django 5.0.1 on 2026-03-10 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tvshow', 'TV Show')], max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist',
                'indexes': [models.Index(fields=['user'], name='watchlist_user_id_c64328_idx'), models.Index(fields=['content_id', 'content_type'], name='watchlist_content_8e39fc_idx')],
                'unique_together': {('user', 'content_id', 'content_type')},
            },
        ),
    ]
