# Generated by Django 5.0.1 on 2026-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
