# Generated by Django 5.0.1 on 2026-03-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_embedding_tvshow_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tvshow', 'TV Show')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('genres', models.JSONField(default=list)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('popularity', models.FloatField(default=0.0)),
                ('vote_average', models.FloatField(default=0.0)),
                ('release_date', models.CharField(blank=True, max_length=20)),
                ('embedding', models.JSONField()),
            ],
            options={
                'db_table': 'content_embeddings',
                'indexes': [models.Index(fields=['content_type'], name='content_emb_content_e3d8d6_idx'), models.Index(fields=['popularity'], name='content_emb_popular_7f8d46_idx')],
                'unique_together': {('tmdb_id', 'content_type')},
            },
        ),
    ]
