# Generated by Django 5.0.1 on 2026-03-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_chatsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_session_70d2c0_idx',
            old_name='chat_messages_session_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_sessio_user_id_54b88f_idx',
            old_name='chat_sessions_user_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_content_a38190_idx',
            old_name='reviews_content_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_user_id_79db63_idx',
            old_name='reviews_user_idx',
        ),
    ]
